### ISSUE TITLE
Merge API function not working

### ISSUE THREAD

**Issue by Skilly146** [Tsangares/stoned_ape_tools#10]
When someone sends you an api code the "merge api:API" button is completely unresponsive, even if you are already looking at their scanning data with the "view as api:API" button which still works.

**Comment by Tsangares** [comment]
I will get on this ASAP

**Comment by AStonedApe** [comment]
Merge seems to be working now. Is this issue still a problem or should we close it?

**Comment by Tsangares** [comment]
Yes, we can reopen if it breaks.
