### ISSUE TITLE
Ledger showing error

### ISSUE THREAD

**Issue by krajniak** [Tsangares/stoned_ape_tools#2]
2.10 does not show ledger on chrome and opera on macos:
Exception:

Uncaught TypeError: Cannot read properties of undefined (reading 'addChild')
    at widget.roost (crux.js:83:17)
    at renderLedger (intel.js:138:66)
widget.roost @ crux.js:83
renderLedger @ intel.js:138
setTimeout (async)
(anonymous) @ intel.js:1517

**Comment by Tsangares** [comment]
Hello, could you try clearing your cache? Or using incognito mode ?

**Comment by krajniak** [comment]
Yup, the same thing
________________________________
Od: William Wyatt ***@***.***>
Wysłane: Saturday, October 8, 2022 7:01:17 PM
Do: Tsangares/stoned_ape_tools ***@***.***>
DW: krajniak ***@***.***>; Author ***@***.***>
Temat: Re: [Tsangares/stoned_ape_tools] Ledger showing error (Issue #2)


Hello, could you try clearing your cache? Or using incognito mode ?

**Comment by Tsangares** [comment]
Could you try typing into the console `renderLedger()` and see if the ledger re-appears in the menu?

**Comment by Tsangares** [comment]
I will install opera to see if I can replicate it.

**Comment by krajniak** [comment]
I’ll try when I’ll get to my computer
________________________________
Od: William Wyatt ***@***.***>
Wysłane: Saturday, October 8, 2022 7:27:27 PM
Do: Tsangares/stoned_ape_tools ***@***.***>
DW: krajniak ***@***.***>; Author ***@***.***>
Temat: Re: [Tsangares/stoned_ape_tools] Ledger showing error (Issue #2)


Could you try typing into the console renderLedger() and see if the ledger re-appears in the menu?

**Comment by Tsangares** [comment]
It will take 3-5 days for google to code review or you can install this plugin from github.

**Comment by Tsangares** [comment]
Hey, actually they just published my change. Could you clear the cache and test the plugin version 2.11?

**Comment by krajniak** [comment]
Yup, I think it's working

sob., 8 paź 2022 o 23:20 William Wyatt ***@***.***>
napisał(a):

**Comment by Tsangares** [comment]
Great!
