### ISSUE TITLE
Ship counts being multiplied by 10 after fraction update

### ISSUE THREAD

**Issue by Skilly146** [Tsangares/stoned_ape_tools#24]
Accidentally made two issues, go to #23 

## What

Ship totals are being multiplied by ten as noticed by gb on the forum and confirmed by me in a 64p game with a photo (Below). the star only has 106 ships according to the map but the edited star counter says 1060 ships.
![Screenshot_20221128_111221](https://user-images.githubusercontent.com/68225269/204463452-0bc229e4-8b50-4daa-8877-cfccb7b0a656.png)

## How

Seems like the extension is just adding an extra digit (Possibly adding the string "0.fraction" instead of just ".fraction") or possibly multiplying by 10 but that doesn't seem likely

**Comment by AStonedApe** [comment]
Pretty sure this one is fixed. Can I close it?

**Comment by Tsangares** [comment]
Finished with 2.18. Duplicate #23
