### ISSUE TITLE
Missing Combat Calculator Button and Help Button

### ISSUE THREAD

**Issue by rworkm** [Tsangares/stoned_ape_tools#8]
On the planet information screen there is a button for the combat calculator and help button.  Typically these are on the top right near the X button.  With the extension on these buttons are missing.  Happens both in real time games and turn based.

**Comment by Tsangares** [comment]
Could you possible send me the console output?

**Comment by rworkm** [comment]
[np.ironhelmet.com-1665755303650.log](https://github.com/Tsangares/stoned_ape_tools/files/9786913/np.ironhelmet.com-1665755303650.log)

**Comment by Tsangares** [comment]
Got it, you must disable or remove Neptunes Pride Agent. 
Either Stoned Ape Tools or Neptunes Pride Agent; not both. 

But thank you, i will make the program put an alert up disabled stoned ape tools if it can detect Neptunes Pride Agent.

**Comment by Tsangares** [comment]
Let me know if this is causing the issue. Your solution should be disabling or removing NPA.

**Comment by rworkm** [comment]
NPA was and is disabled.  I tried removing it completely and clearing cache and hard reload.  Issue persists.

**Comment by Tsangares** [comment]
Could you send the log again?

**Comment by rworkm** [comment]
[np.ironhelmet.com-1665781862804.log](https://github.com/Tsangares/stoned_ape_tools/files/9790079/np.ironhelmet.com-1665781862804.log)

**Comment by Tsangares** [comment]
Oh I know what happened. Their z-index got pushed back when i fixed a bug in turn based games.

I will hot fix asap.

**Comment by Tsangares** [comment]
Okay, I fixed it (I think). I published a new version 2.13 which has to go through google code review. This takes 3-5 days, I will ping you and ask if its fixed on your end.

**Comment by Tsangares** [comment]
It should be updated. Could you check?

**Comment by rworkm** [comment]
That worked!
